export default {
  useNextVariants: true,
  fontFamily: [
    'Helvetica',
    'Arial',
    'sans-serif',
  ].join(','),
  body1: {
    fontFamily: '"Helvetica", "Arial", sans-serif',
    fontWeight: 'regular',
    fontSize: '1rem',
    color: '#4A4F55',
  },
  body2: {
    fontFamily: '"Helvetica", "Arial", sans-serif',
    fontWeight: 'regular',
    fontSize: '1rem',
    color: '#4A4F55',
  },
  h1: {
    fontFamily: '"Helvetica", "Arial", sans-serif',
    fontWeight: '900',
    textTransform: 'uppercase',
    color: '#4A5055',
    fontSize: '1.625rem',
    lineHeight: '1.2',
    paddingTop: '24px',
    letterSpacing: '0.03em',
    width: '100%',
  },
  h2: {
    fontFamily: '"Helvetica", "Arial", sans-serif',
    fontWeight: '900',
    textTransform: 'uppercase',
    color: '#4A5055',
    fontSize: '1.5rem',
    letterSpacing: '0.03em',
  },
  h3: {
    fontFamily: '"Helvetica", "Arial", sans-serif',
    fontWeight: '900',
    textTransform: 'uppercase',
    color: '#4A5055',
    fontSize: '1.375rem',
    letterSpacing: '0.03em',
  },
  h4: {
    fontFamily: '"Helvetica", "Arial", sans-serif',
    fontWeight: '900',
    textTransform: 'uppercase',
    color: '#4A5055',
    fontSize: '1.25rem',
    letterSpacing: '0.03em',
  },
  h5: {
    fontFamily: '"Helvetica", "Arial", sans-serif',
    fontWeight: '900',
    textTransform: 'uppercase',
    color: '#4A5055',
    fontSize: '1.125rem',
    marginTop: '1em',
    marginBottom: '1em',
    letterSpacing: '0.03em',
  },
  h6: {
    fontFamily: '"Helvetica", "Arial", sans-serif',
    fontWeight: '900',
    textTransform: 'uppercase',
    color: '#4A5055',
    fontSize: '1rem',
    letterSpacing: '0.03em',
  },
  caption: {
    fontFamily: '"Helvetica", "Arial", sans-serif',
  },
  subtitle1: {
    fontFamily: '"Helvetica", "Arial", sans-serif',
  },
  subtitle2: {
    fontFamily: '"Helvetica", "Arial", sans-serif',
  },
};
