export const FETCH_DASHBOARD = 'FETCH_DASHBOARD';
export const FETCH_DASHBOARD_LOADING = 'FETCH_DASHBOARD_LOADING';
export const FETCH_DASHBOARD_SUCCESS = 'FETCH_DASHBOARD_SUCCESS';
export const FETCH_DASHBOARD_FAILURE = 'FETCH_DASHBOARD_FAILURE';
export const RESET_ACTIVE_DASHBOARD = 'RESET_ACTIVE_DASHBOARD';